[package]
name = "jatom-lang"
version = "0.1.0"
edition = "2021"

[build-dependencies]
lalrpop = { version = "=0.22.1" }

[dependencies]
ordered-float = "5.0.0"

[dependencies.lalrpop-util]
version = "=0.22.1"

features = [
    "unicode",
    "lexer",
]
