[package]
name = "jatom-lang"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["jatom-parser"]

[workspace.dependencies]
ordered-float = "5.0.0"

[dependencies]
ordered-float = { workspace = true }
jatom-parser = { path = "jatom-parser" }
smol_str = "0.3.2"
itermaps = "0.3.3"
