[package]
name = "jatom-parser"
version = "0.1.0"
edition = "2021"

[build-dependencies]
lalrpop = { version = "=0.22.1" }

[dependencies]
ordered-float = { workspace = true }

[dependencies.lalrpop-util]
version = "=0.22.1"

features = [
    "unicode",
    "lexer",
]
